main: com.minegusta.mgpvpworld.main.Main
name: MGPvPWorld
version: ${project.version}
author: janie177
commands:
  pvpreload:
    usage: /pvpreload
    description: Reload MGPvPWorld.
    default: op
  pvp:
    usage: /PvP
    description: Teleport to the PvP world.
    default: false
    permission: minegusta.pvptele